### ISSUE TITLE
value is max but then dot position is min

### ISSUE THREAD

**Issue by xkrabb** [NightCatSama/vue-slider-component#10]
（version 1.x）in my application,  ready function
 `this.size = this.direction === 'vertical' ? this.$els.elem.offsetHeight : this.$els.elem.offsetWidth` 
the size is 0,  maybe the dom is not ready

**Comment by NightCatSama** [comment]
In the simplest case of test is normal,  Do you have to use `v-show`,  `v-if`, or ajax asynchronous requests.

**Comment by NightCatSama** [comment]
Oops, if the component initialization is `:show="false"` or in a `v-show="false"` container, will appear abnormal. 

The solution:
1. using `v-if` instead of `v-show` or `:show` .
2. After the set `v-show="true“` or `:show="true"`, to call the `refresh` method.
example: 
```
this.show = true
this.$nextTick(() => {
    this.$refs.slider.refresh()
})
```

After that I may update components, use the second solution.

**Comment by xkrabb** [comment]
@NightCatSama thanks

**Comment by jersobh** [comment]
Hi there,

We may have found a better solution for this issue. you can just put the "this.$refs.slider.refresh()" on the mounted(), so you'll assure that everything has already been created. Like this: 

mounted (){
    this.$refs.slider.refresh()
    },

**Comment by NightCatSama** [comment]
I think it should be no good, as long as the components do not have real rendering on the page, `refresh()` is unable to get `offsetWidth` and `offsetHeight`.

For example component is in a `v-show="false"` or `display: none` container, he will perform mounted but is unable to get `offsetWidth` and `offsetHeight`, because he has not been rendered to the page.
