### ISSUE TITLE
Log warning when slider discards value when < min or > max

### ISSUE THREAD

**Issue by kbirk** [NightCatSama/vue-slider-component#144]
Currently if a value is provided to the slider that is less than the `min`, or greater than the `max`, the slider seems to default the value to `undefined` and eventually `0`.

In my situation this was due to a race condition where the computed value for the `min` / `max` was computed after the computed value for the `model` and initial `value` property. Due to the how vue caches computed values, eventually when the `min` / `max` were computed, but the `model` retained the defaulted `0` value.

I think at the very least the slider should output a warning, or due to the implicit relationship between `min`, `max` and the `value` of the slider, recompute the `value` when the `min` and `max` are modified.

**Comment by NightCatSama** [comment]
In fact, when the value is less than min or greater than max, it automatically corrects the value equal to min or max. But I just found a bug that does not correct itself when the value is equal to the default value (Because when the value has not changed, the components do not do anything).

I will fix this, and will print a warning in the console.

**Comment by NightCatSama** [comment]
You can update to version 2.5.0.
