### ISSUE TITLE
Change onclick not on mouseup 

### ISSUE THREAD

**Issue by diimdeep** [NightCatSama/vue-slider-component#172]
I notice that in all demos, change happen only after mouse click, I want as soon as mouse button is pressed

**Comment by NightCatSama** [comment]
`Mousedown` and `mouseup` trigger on the same element will trigger the click event.

Bind the mouseup event on the component will not change the value...

**Comment by diimdeep** [comment]
Sorry, I have to clarify.
Slider do not behave as native <input type=slider>.
When you click in different area than knob(to change value), it do not change value immediately(have to release mouse button), also after that if you keep press mouse down you can't just move it to change value.

**Comment by NightCatSama** [comment]
Yes, this is currently the case. The click event does not determine when it was pressed until it was released.

**Comment by jordangeizer** [comment]
+1 for this. 

@NightCatSama could we have an option for this in the future?

The default behaviour in both native browser html sliders and other polyfills (https://rangeslider.js.org) is to update the value/dot position on mousedown not on mouseup. 

I think it's a much better user experience to be able to click down on a part of the slider, have the slider update its value and dot position, then be able to continue dragging to refine the value.

Otherwise you have to click twice. 
A first click to get the dot in position and then a second click on the dot to refine the value.
