### ISSUE TITLE
Values reverse when dots cross each other

### ISSUE THREAD

**Issue by michalhlavka** [NightCatSama/vue-slider-component#207]
I've got one question, it's possible to disable these values reverse? I am not even able to find part of the code which this logic does.

Thanks for the answer.

**Comment by michalhlavka** [comment]
Here is an example if we did not understand
https://screencast.com/t/67drt5y231wz

**Comment by NightCatSama** [comment]
What version do you use?

**Comment by michalhlavka** [comment]
`^2.6.2`

**Comment by NightCatSama** [comment]
What do you mean by the reverse value?

**Comment by NightCatSama** [comment]
Not currently available.

**Comment by michalhlavka** [comment]
But I am asking, which part of the code does this logic.

**Comment by NightCatSama** [comment]
Because there is no difference in dot, it is very troublesome to implement this function at present.

It's the code for the dot swap location, maybe you can do something by emitting an event.
[L55-L756](https://github.com/NightCatSama/vue-slider-component/blob/master/src/vue2-slider.vue#L755-L756) and [L765-L766](https://github.com/NightCatSama/vue-slider-component/blob/master/src/vue2-slider.vue#L765-L766)

**Comment by michalhlavka** [comment]
Alright thanks.
