### ISSUE TITLE
Snappy Dot

### ISSUE THREAD

**Issue by thedanotto** [NightCatSama/vue-slider-component#234]
Sorry if I missed this in the documentation or other issues.

In all of the examples I've seen, dragging the dots result in very fluid motion upon the slider's axis and upon releasing the dot transitions to the nearest point. 

I would like a slightly different functionality. While I'm dragging, I would like the dot to snap into the nearest value. So if I have a slider with min of 0 and max of 10, while I am dragging the dot, it would only have 11 possible positions along the axis.

Does that make sense? / is that possible?

**Comment by NightCatSama** [comment]
Do you mean that she needs to get the value of the nearest point and does not want the slider to slide to that value?

**Comment by thedanotto** [comment]
Yes, exactly!

**Comment by rainabba** [comment]
If I'm here for the same reasons as I suspect, I believe a better way to say it would be, "snap to the nearest value, both visually and the value." I'm thinking that I'd like to populate "values" with an array of selectable values, rather than min/max. 

Essentially, I want a <select> element in slider form and "values" would effectively be my "options" param on that select.

@thedanotto That what you're going for, or something different?

**Comment by NightCatSama** [comment]
In the latest version, you can do it with `marks` and `included`.

<https://nightcatsama.github.io/vue-slider-component/#/basics/marks>
