### ISSUE TITLE
Merge Formatter

### ISSUE THREAD

**Issue by pawmanaloto** [NightCatSama/vue-slider-component#502]
Is there any way we can get the mergeFormatter back on the props for range mode? I know this was an option before the v3.

**Comment by NightCatSama** [comment]
Sorry, I've tried and this is a difficult feature to implement.

Because the tooltip is currently within the slider element, and there can be more than two sliders, making this related calculation difficult to implement.

A relatively simple merge can be done with a slot: 🤕 

<https://jsfiddle.net/ykpLdjmw/>
